export const RECENTLY_ADDED_CUSTOMERS = 'app/Customer/RECENTLY_ADDED_CUSTOMERS';
export const RECENTLY_ADDED_CUSTOMERS_SUCCESS = 'app/Customer/RECENTLY_ADDED_CUSTOMERS_SUCCESS';
export const RECENTLY_ADDED_CUSTOMERS_FAILURE = 'app/Customer/RECENTLY_ADDED_CUSTOMERS_FAILURE';
export const RECENTLY_ADDED_SELECT_CUSTOMERS = 'app/Customer/RECENTLY_ADDED_SELECT_CUSTOMERS';

